### ISSUE TITLE
exception implement net.Error

### ISSUE THREAD

**Issue by ljun20160606** [cloudwego/netpoll#270]
**Is your feature request related to a problem? Please describe.**
I'm trying to replace dialer with netpoll.DialConnection. I found that the client I'm using depends on the interface net.Error.

**Describe the solution you'd like**

After read the related implement of exception, I noticed that we have tried to wrap a syscall.Errno which has implemented net.Error.

Is it possible to have a quick implement that looks like as follows?

```golang
func (e *exception) Timeout() bool {
	return e.timeout() || e.no.Timeout()
}

func (e *exception) Temporary() bool {
	return e.timeout() || e.no.Temporary()
}

func (e *exception) timeout() bool {
	return e.no == ErrReadTimeout || e.no == ErrDialTimeout || e.no == ErrWriteTimeout
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by joway** [comment]
Where you get the error that need implement net.Error?

**Comment by ljun20160606** [comment]
https://github.com/redis/go-redis/blob/50f04c14dee344147e9cf061f752ee913fd6c3ee/error.go#L104-L106
@joway

**Comment by yicixin** [comment]
This is also what I want, I've encountered a problem related to the `crypto/tls` package.

The crux of the problem is that `netpoll.Exception` does not implement `net.Error`, which leads to the error being continuously stored by `tls.Conn` and persistently reported in subsequent Read.You can find the code at [here](https://github.com/golang/go/blob/2184a394777ccc9ce9625932b2ad773e6e626be0/src/crypto/tls/conn.go#L633C5-L633C5)

**Comment by joway** [comment]
fixed and merged @yicixin @ljun20160606 thanks for your advice
