### ISSUE TITLE
Sincerely ask for advice on LinkBuffer design ideas

### ISSUE THREAD

**Issue by Trinoooo** [cloudwego/netpoll#347]
I have a question while reading the LinkBuffer source code. I tried to have my own understanding, but I still really want to know the authoritative explanation from the official maintainer. I would like to express my gratitude here :)

The question is why `Next` uses memory pool management only when the space size N is greater than or equal to 1K and less than or equal to 8M when allocating read space?
I have two ideas: The first idea is that the hit rate of memory blocks in the size range of 1K to 8M is high, and caching the already applied memory space through pooling technology can significantly improve performance, but I have no data to support my guess; The second idea is that caching memory blocks that are too small will cause internal fragmentation and reduce memory allocation and garbage collection performance.

Finally, thank you for answering my questions!

**Comment by joway** [comment]
because use `b.caches` will cause more memory used. 

if n < 1k , go mem allocator will not have too much overhead to alloc small space. so just let it use the native allocator.
if n > 8MB, cache will hold more memory and maybe cause OOM. so it not worth to take the OOM risk to gain performance benifit.
